name: C/C++ CI

on:
  push:
    branches: [ "main", "cmake" ]
  pull_request:
    branches: [ "main", "cmake" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: cmake -B build
    - name: make
      run: cmake --build build
    - name: cpack
      run: cpack --config ./build/CPackConfig.cmake -G DEB 
    # - name: make distcheck
    #   run: make distcheck
    - name: LS
      run: tree
    - name: Upload DEB package
      uses: actions/upload-artifact@v4
      with:
        name: deb-package
        path: |
            "./usbresetservice*.deb"
        # "oculos_*.zip"
        retention-days: 5
